### ISSUE TITLE
"status":"The location for requested IP can not be found."

### ISSUE THREAD

**Issue by Kirmas** [seniverse/seniverse-api#3]
Hello. I`m not shore that this is good place for my issue but I have no other ideas.

I have device that use your api for weather detection. But for me this is not working. Because:
"status":"The location for requested IP can not be found.". 
As I understand you must add IP range to BD. Or something else.
You can check my IP using https://www.ip2location.com/84.234.109.41 this is Kyiv, Ukraine. 

My device use https://api.seniverse.com/v3/weather/now.json?key=SxTmZ8QZRW5fvG_C0&location=84.234.109.41&language=en&unit=c&start=0&days=5 this request. I used code snipping to get this

**Comment by shianqi** [comment]
try 109.41.84.234

**Comment by Kirmas** [comment]
This is not a question of request params. Cos I cant change this in third party devise like: [ARNY AVD-1060](https://arny.com.ua/ip-videodomofony/avd-1060-2mpx-wifi ) If you use came kinde of service to resolve IP to the location please tell me. I understand that this is out of scope of your company. But I dont know what to do to resolve my situation.

**Comment by Kirmas** [comment]
I found the way (using proxy and other black magic) change IP that my intercom use. This is not very useful but this issue can be closed.
